<?xml version="1.0"?>
<package format="3">
  <name>farm_world</name>
  <version>0.1.0</version>
  <description>Farm environment for ROS 2 Humble and Gazebo Classic 11.</description>
  <maintainer email="tianwei.niu@cau.edu.cn">Tianwei Niu</maintainer>
  <license>MIT</license>
  <license>See NOTICE.md</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
  </export>
</package>
